config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  root to: "home#index"
  post "/cart/:book_id" => "home#add_to_cart", as: :add_to_cart
  get "/cart" => "home#cart", as: :show_cart
  patch "/cart/items/:cart_item_id" => "home#update_quantity", as: :update_cart_item
  post "/charge" => "home#charge"

  get "/receipts/:stripe_charge_id" => "home#receipt" , as: :receipt

end

app/models/book.rb
class Book < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search,
                  :against => [:title, :author],
                  :using => {
                    :tsearch => {
                      :prefix => true,
                      :dictionary => "english"
                      }
                  }

  mount_uploader :image, PhotoUploader

  def self.query(params)
    if params[:query].blank?
      Book.all
    else
      Book.search(params[:query])
    end
  end

  def price
    sales_price_in_cents / 100.0
  end

  def msrp
    msrp_in_cents / 100.0
  end

  def percent_off
    (msrp - price) / msrp * 100.0
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items

  def total
    cart_items.map(&:total).sum
  end

  def total_in_cents
    (total * 100).to_i
  end
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :book
  belongs_to :cart

  def total
    quantity * book.price
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :book

  def price
    price_paid_in_cents / 100.0
  end

  def total
    price_paid_in_cents * quantity/ 100.0
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  def total
    line_items.map(&:total).sum
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :verify_authenticity_token, only: [:charge]

  respond_to :html, :json
  
  def index
    @books = Book.query(params).page(params[:page])
    respond_with @books
  end

  def charge

    cart = find_cart

    Stripe.api_key = "sk_test_4ZTpoMNU3PGxXxKgxlIW0sXA"

    # Get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create the charge on Stripe's servers - this will charge the user's card
    begin
      charge = Stripe::Charge.create(
        :amount => cart.total_in_cents, # amount in cents, again
        :currency => "usd",
        :card => token,
        :description => "Scholastic Books"
      )
    rescue Stripe::CardError => e
      # The card has been declined
    end

    # 1. create charge
    # 2. create order
    @order = Order.new(stripe_charge_id: charge.id)
    cart.cart_items.each do |ci|
      @order.line_items.build(book: ci.book, quantity: ci.quantity, price_paid_in_cents: ci.book.sales_price_in_cents)
    end
    @order.save

    # 3. remove cart
    session[:cart_id] = nil
    cart.destroy

    # 4. update inventory
    @order.line_items.each do |li|
      quantity_new = li.book.inventory - li.quantity
      li.book.update(inventory: quantity_new)
    end

    redirect_to receipt_path(stripe_charge_id: @order.stripe_charge_id)


  end

  def cart
    # get books from cart
    # show the books
    @cart = find_cart
  end

  def add_to_cart
    # find book from params[:book_id]
    book = Book.find(params[:book_id])

    # find the cart
    cart = find_cart

    # add to cart
    cart.cart_items.create quantity: 1, book: book


    # redirect_to show cart page
    redirect_to show_cart_path

  end

  def update_quantity
    cart_item = CartItem.find(params[:cart_item_id])
    # "cart_item"=>{"quantity"=>"2"},
    # {"quantity"=>"2"}
    cart_item.update(params.require(:cart_item).permit(:quantity))
    cart.save
  end

  def receipt
    @order = Order.find_by stripe_charge_id: params[:stripe_charge_id]
  end

  def find_cart
    if session[:cart_id].present?
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create!
      session[:cart_id] = cart.id
    end
    cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_cart.html.erb
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Book</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @cart.cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.book.title %></td>
        <td>
          <%= simple_form_for cart_item, url: update_cart_item_path(cart_item), remote: true do |f| %>
          <%= f.input :quantity, label: false, as: :select, collection: (1..cart_item.book.inventory) %>
          <%= f.submit %>
          <% end %>
        </td>
        <td><%= number_to_currency cart_item.book.price %></td>
        <td><%= number_to_currency cart_item.total %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total</strong></td>
      <td><%= number_to_currency @cart.total %> </td>
    </tr>
  </tbody>
</table>



<p>

  <form action="/charge" method="POST">
    <script
      src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="pk_test_4ZTpi4sGW2JMFGrxlNn6HnQ7"
      data-name="Scholastic"
      data-description="PAY ME FOOL! (<%= number_to_currency @cart.total %>)"
      data-amount="<%= @cart.total_in_cents %>">
    </script>
  </form>



  or
  <%= link_to "Continue Shopping", root_path %>
</p>

app/views/home/cart.html.erb
I AM THE CART. BOW BEFORE MY AWESOMENSS

<div class="cart">
<%= render partial: 'cart' %>
</div>

app/views/home/index.html.erb
<div class="row">
  <% @books.each do |book| %>
  <div class="col-sm-6 col-md-4">

    <div class="thumbnail">
      <%= link_to book.image.url, class: "fancybox" do %>
      <%= image_tag book.image.url(:view) %>
      <% end %>
      <div class="caption">
        <h3><%= book.title %></h3>
        <p>
          <small><%= book.author %></small><br/>
        </p>
        <p>
          <%= number_to_currency book.price %>
          <span class="label label-info">Save <%= number_to_percentage(book.percent_off, precision: 0)    %></span>
          <span class="muted">over <strike><%= number_to_currency book.msrp %></strike></span>
        </p>

        <% if book.inventory == 0 %>
        ALL GONE SUCKA
        <% else %>

          <% if book.inventory <= 5 %>
            <p>Only <%= pluralize book.inventory, 'copy' %> left!</p>
          <% end %>
          <p>
            <%= link_to add_to_cart_path(book_id: book.id), method: :post,  class: "btn btn-large btn-success btn-block" do %>
              <span class='glyphicon glyphicon-shopping-cart'></span> Add to Cart
            <% end %>
          </p>

        <% end %>
      </div>
    </div>
  </div>
  <% end %>

</div>
<%= paginate @books %>

app/views/home/receipt.html.erb
<p class="page-title">
  <h1>Receipt: <%= @order.created_at.strftime("%A, %b %d %Y") %></h1>
</p>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Book</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @order.line_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.book.title %></td>
        <td><%= cart_item.quantity %>
        </td>
        <td><%= number_to_currency cart_item.price %></td>
        <td><%= number_to_currency cart_item.total %></td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td></td>
      <td><strong>Total</strong></td>
      <td><%= number_to_currency @order.total %> </td>
    </tr>
  </tbody>
</table>



<p>


  <%= link_to "Continue Shopping", root_path %>
</p>

app/views/home/update_quantity.js.erb
$(".cart").html("<%= j render partial: 'cart' %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scholastic</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'  %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <p class="page-title">

        <h1><%= link_to "Scholastic", root_path %></h1>
        <p class="pull-right">
          <a class="fancybox-media" href="http://maps.google.com/maps?q=Start+Houston&t=h&z=17">Google Mappit</a>
        </p>
      </p>
    </div>
  </div>
  <div class="row">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= form_tag root_path, method: :get do %>
        <div class="form-group  has-feedback">
        <label class="control-label sr-only" for="inputSuccess5">Hidden label</label>
        <%= text_field_tag :query, params[:query], class: "form-control typeahead", placeholder: "Search yo" %>
        <span class="glyphicon glyphicon-search form-control-feedback"></span>
      </div>
      <% end %>

      <% if params[:query].present? %>
        We found <%= pluralize @books.length, 'book' %>.
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>

</body>
</html>